version: '3.6'

services:
  web:
    build: .
    command: sh -c "/code/run.sh"
    volumes:
      - ./backend:/code/backend
    ports:
      - '8000:8000'
    environment:
      - DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5436:5436'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A app worker --loglevel=info -B -c 1 -E
    restart: always
    env_file:
      - .env
    ports:
      - "5566:5566"
    depends_on:
      - redis
    volumes:
      - ./backend:/code/backend

  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - ./backend:/code/backend
    environment:
      - DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
