version: '3.6'

services:

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

#  celery:
#    build: ./
#    command: celery -A app worker -l info -B
#    restart: always
#    volumes:
#      - './:/app/'
#    env_file:
#      - .env
#    ports:
#      - "5566:5566"
#    depends_on:
#      - postgres
#      - redis

#  celery-beat:
#    build: ./
#    command: celery -A app beat -l info
#    volumes:
#      - './:/app/'
#    environment:
#      - DEBUG
#      - SECRET_KEY
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#    depends_on:
#      - redis
