version: '3.6'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

#  web:
#    build: .
#    command: chmod +x "/code/run.sh"
#    restart: always
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#    container_name: django_web
#    volumes:
#      - ./backend:/code/backend
#    ports:
#      - '8000:8000'

  celery:
    build: .
    command: celery -A app worker --loglevel=info -B -c 1 -E
    restart: always
    env_file:
      - .env
    ports:
      - "5566:5566"
    depends_on:
      - postgres
      - redis
#      - web
    volumes:
      - ./backend:/code/backend
