# Generated by Django 4.1 on 2022-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=100, verbose_name='USD')),
                ('rub', models.DecimalField(decimal_places=4, max_digits=100, verbose_name='RUB')),
                ('dated', models.DateField(auto_now_add=True, verbose_name='Дата курса')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курс валют',
            },
        ),
    ]
